server:
  port: 8081

spring:
  main.banner-mode: 'off'
  kafka:
    bootstrap-servers: 'kafka:9092'
    consumer:
      group-id: 'TELEGRAM'
      properties.spring.json.trusted.packages: "*"

logging.level:
  root: INFO

ar:
  vicria:
    adapter:
      telegram:
        botUserName: subte_arg_bot
        botToken:
        subtePost: 'http://localhost:8082/distance/count'
        subteGet: 'http://localhost:8082/stations/all'
