server:
  port: 8081

spring:
  main.banner-mode: 'off'
  kafka:
    bootstrap-servers: 'kafka:9092'
    consumer:
      group-id: 'TELEGRAM'
      properties.spring.json.trusted.packages: "*"

logging.level:
  root: INFO

ar:
  vicria:
    kafka:
      roadMessageTopic: 'telegram_road_message_edit_topic'
      subteRoadTopic: 'subte_road_topic'
    adapter:
      telegram:
        botUserName: subte_arg_bot
        botToken:
    subte:
      client:
        enabled: true
        url: 'http://localhost:8082'
