INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'Retiro');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'General San Martín');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'Lavalle');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'Diagonal Norte');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'Avenida de Mayo');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'Moreno');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'Independencia');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'San Juan');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'C🔵', 'Constitución');

INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Plaza de Mayo');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Perú');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Piedras');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Lima');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Sáenz Peña');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Congreso');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Pasco');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Alberti');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Plaza Miserere');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Loria');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Castro Barros');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Río de Janeiro');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Acoyte');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Primera Junta');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Puán');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'Carabobo');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'San José de Flores');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'A🔵', 'San Pedrito');

INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Plaza de los Virreyes');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Varela');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Medalla Milagrosa');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Emilio Mitre');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'José María Moreno');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Avenida La Plata');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Boedo');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'General Urquiza');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Jujuy');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Pichincha');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Entre Ríos-Rodolfo Walsh');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'San José');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Independencia');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Belgrano');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Bolívar');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Correo Central');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Catalinas');
INSERT INTO subte_bot.subte_station (id, line, name) VALUES (gen_random_uuid()::text, 'E🟣', 'Retiro');

