SELECT insert_connection('Pueyrredón', 'B🔴', 'Corrientes', 'H🟡',  null, null, 2.47);
SELECT insert_connection('Pueyrredón', 'B🔴', 'Pasteur AMIA', 'B🔴',  'Leandro N. Alem', 'B🔴', 2.47);
SELECT insert_connection('Pasteur AMIA', 'B🔴',  'Pueyrredón', 'B🔴', 'Juan Manuel de Rosas Villa Urquiza', 'B🔴', 2.02);
SELECT insert_connection('Pasteur AMIA', 'B🔴',  'Callao', 'B🔴', 'Leandro N. Alem', 'B🔴', 2.02);
SELECT insert_connection('Callao', 'B🔴', 'Pasteur AMIA', 'B🔴', 'Juan Manuel de Rosas Villa Urquiza', 'B🔴', 2.02);
SELECT insert_connection('Callao', 'B🔴', 'Uruguay', 'B🔴', 'Leandro N. Alem', 'B🔴', 2.02);
SELECT insert_connection('Uruguay', 'B🔴', 'Callao', 'B🔴', 'Juan Manuel de Rosas Villa Urquiza', 'B🔴', 2.02);
SELECT insert_connection('Uruguay', 'B🔴', 'Carlos Pellegrini', 'B🔴', 'Leandro N. Alem', 'B🔴', 2.02);
SELECT insert_connection('Carlos Pellegrini', 'B🔴', 'Uruguay', 'B🔴', 'Juan Manuel de Rosas Villa Urquiza', 'B🔴', 2.02);
SELECT insert_connection('Carlos Pellegrini', 'B🔴', '9 de Julio', 'D🟢', null, null, 2.02);